services:
  - type: web
    name: smart-attendance-system
    env: python
    buildCommand: "bash build.sh"
    startCommand: "streamlit run app.py --server.port $PORT --server.address 0.0.0.0"
    envVars:
      - key: MONGO_URI
        sync: false
